hugoblox:
  schema: "2.0"
  identity:
    name: Yongqi Zhang
    type: person
    tagline: HCI + AI Resesarcher
    description: |
      I am currently seeking new professional opportunities and would love to connect. Please feel free to reach out or download my CV.
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  # imaging:
  #   resampleFilter: "Lanczos"
  #   quality: 100  # Setting this to 100 prevents almost all compression artifacts
  #   hint: "picture"